### ISSUE TITLE
Contribute upstream?

### ISSUE THREAD

**Issue by copumpkin** [BigBrassBand/jgit-codecommit#1]
I just found this repo while trying to figure out how to integrate CodeCommit with JGit and it looks great. Have you considered submitting it upstream? They have an open ticket for good CodeCommit support so it seems like it would be a welcome contribution: https://bugs.eclipse.org/bugs/show_bug.cgi?id=472415

Either way, thanks!

**Comment by brainopener** [comment]
Hello!

I'll bring it up with my team. I don't know if there's anyone who has time to do it.

**Comment by copumpkin** [comment]
Cool, thanks for the prompt reply! If you could clarify the license on this code (and/or ensure it's compatible with JGit's) someone else could possibly take care of submitting the pull request upstream.

**Comment by brainopener** [comment]
That's a good idea. I just added a LICENSE -- it's the same as jgit itself.

**Comment by copumpkin** [comment]
Awesome, thanks! I'll see how ambitious I'm feeling 😄
